import type { Chart } from '../chart/chart.js';
import { BODY_NAME, SIGN_NAMES, fmtDegInSign, fmtOrb, signIndex } from '../render/glyphs.js';
import { tensionReport } from './composer.js';
import { lunationPhase } from './dossiers.js';
import type { ChartMeta } from '../ui/state.js';

/**
 * Markdown snapshot of a computed chart, designed to paste into an AI
 * conversation (user test part 2: "take this snapshot of your chart …
 * a personality profile using IFS — like we did before with Claude").
 * Raw factors only, no interpretations: the receiving model should
 * work from the astrology, not from our prose.
 */
export function chartSnapshot(chart: Chart, meta: ChartMeta): string {
  // drop the U+FE0E text-presentation selector that fmtDegInSign embeds
  const strip = (s: string) => s.replace(/︎/g, '').trim();
  const lines: string[] = [];
  lines.push(`# Natal chart — ${meta.name || 'unnamed'}`);
  lines.push(`Born ${meta.date} ${meta.time} (UTC${meta.offsetMinutes >= 0 ? '+' : ''}${Math.floor(meta.offsetMinutes / 60)}:${String(Math.abs(meta.offsetMinutes % 60)).padStart(2, '0')}) · ${meta.place.name}, ${meta.place.country} · Placidus houses, tropical zodiac.`);
  if (meta.accuracy !== 'exact') {
    lines.push(`Birth-time accuracy: ${meta.accuracy} — treat houses/angles accordingly.`);
  }
  lines.push('', '## Angles');
  lines.push(`- Ascendant: ${strip(fmtDegInSign(chart.houses.asc))}`);
  lines.push(`- Midheaven: ${strip(fmtDegInSign(chart.houses.mc))}`);
  lines.push('', '## Positions');
  for (const p of chart.positions) {
    lines.push(`- ${BODY_NAME[p.body]}: ${strip(fmtDegInSign(p.lon))}, house ${p.house}${p.speed < 0 ? ', retrograde' : ''}`);
  }
  lines.push('', '## Aspects (strongest first, with orb)');
  for (const a of chart.aspects) {
    lines.push(`- ${BODY_NAME[a.a]} ${a.def.name} ${BODY_NAME[a.b]} (orb ${strip(fmtOrb(a.orb))}, ${a.applying ? 'applying' : 'separating'})`);
  }
  const sun = chart.positions.find(p => p.body === 'sun');
  const moon = chart.positions.find(p => p.body === 'moon');
  if (sun && moon) {
    lines.push('', `Lunation phase at birth: ${lunationPhase(sun.lon, moon.lon).name}.`);
  }
  const tensions = tensionReport(chart);
  if (tensions.length) {
    lines.push('', '## Strongest internal contradictions (computed)');
    for (const t of tensions) {
      lines.push(`- ${BODY_NAME[t.a.a]} ${t.a.def.name} ${BODY_NAME[t.a.b]} vs ${BODY_NAME[t.b.a]} ${t.b.def.name} ${BODY_NAME[t.b.b]} — opposed pulls on "${t.theme}"`);
    }
  }
  const emphases = signEmphasis(chart);
  if (emphases) lines.push('', emphases);
  lines.push('', '---',
    'Snapshot generated by Astrodynamics (positions computed offline against JPL/Swiss-validated ephemerides). Interpretations deliberately omitted — please interpret from the raw factors above.');
  return lines.join('\n');
}

function signEmphasis(chart: Chart): string {
  const counts = new Map<number, number>();
  for (const p of chart.positions) {
    const s = signIndex(p.lon);
    counts.set(s, (counts.get(s) ?? 0) + 1);
  }
  const stellia = [...counts.entries()].filter(([, n]) => n >= 3)
    .map(([s, n]) => `${n} bodies in ${SIGN_NAMES[s]}`);
  return stellia.length ? `Sign emphasis: ${stellia.join('; ')}.` : '';
}
